# Generated by Django 3.2.8 on 2022-04-13 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total_price',
            new_name='total_price_of_order',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='finished_time',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='start_time',
        ),
        migrations.AddField(
            model_name='orders',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='In shopping cart', max_length=20),
        ),
    ]
