# Generated by Django 3.2.8 on 2022-04-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220414_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='way_of_pay',
            field=models.CharField(default='Debit Card', max_length=20),
        ),
    ]
