# Generated by Django 3.2.8 on 2022-04-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_is_delivery_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='ssn',
            field=models.CharField(default='', max_length=10),
        ),
    ]
