# Generated by Django 3.2.8 on 2022-04-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dishes',
            name='image',
            field=models.ImageField(default='img\\default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='dishes',
            name='quantity',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
